version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: hcm-postgres
    environment:
      POSTGRES_DB: hcm_development
      POSTGRES_USER: hcm_user
      POSTGRES_PASSWORD: hcm_password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hcm-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hcm_user -d hcm_development"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:8
    container_name: hcm-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hcm.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - hcm-network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  hcm-network:
    driver: bridge
